language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
  - mv build/index.html build/200.html
deploy:
  provider: surge
  project: ./build/
  skip_cleanup: true
  domain: https://react-user.surge.sh
  on:
    branch: master